[package]
name = "provide"
version = "0.1.5"
authors = ["Adam Keating <adamkeating@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
rusoto_core = {version="0.45.0", default_features = false, features=["rustls"]}
rusoto_ssm = {version="0.45.0", default_features = false, features=["rustls"]}
regex = "1.4.2"
clap = "2.33.1"
dirs = "3.0.1"
lazy_static = "1.4.0"
base64 = "0.13.0"
tokio = {version = "0.2.24", features = ["full"]}
